### ISSUE TITLE
[WIP] V2 Code Refactoring

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/Yasui#4]
### Features

* Server Monitor
  - TPS
  - Current Tick speed
  - Entity Amount Counter
  - Entity Tick Time Counter
  - Redstone Event Counter
  - Redstone Tick Time Counter
  - Chunk Tick Time Counter
* Modules
  - Random tick speed auto-adjustments
  - Entity AI Suppressor
  - Entity Culler
  - Redstone Suppressor
  - Command Executor

### Design

The plugin should be modular. It has 3 major parts:

* Status Monitor, that continuously monitors many aspect of the server, and invoke corresponding operations when a rule is met.
* Operations Manager, manages operations, which are the instances of each "feature module" with actual parameters. Operations are used in rules.
* Rules Handler, defines rules in which situation that should apply with one or more operations to maintain the server stability and gaming experience.

### Commands

| Command | Permission | Description |
| --- | --- | --- |
| `/yasui status` | `yasui.command.status` | Shows current server overall status with some statistics. |
| `/yasui chunks [world]` | `yasui.command.chunks` | Shows top-N chunks that consuming most of the tick time. If `[world]` is supplied, shows data for that specific world. Otherwise use the world which the executor is in. |
| `/yasui counter <entity\|redstone> [world]` | `yasui.command.counter` | Shows top-N entity or redstone counter data that consuming most of the tick time. `entity` lists `LivingEntity` and `All Other` categories, while `redstone` lists `Redstone` and `Physics` categories. |
| `/yasui operation <engage\|release> <operation> [world\|all]` | `yasui.command.operation` | Manually engage or release operation to a specific world, or the world which player is in, or all worlds. |
| `/yasui reset` | `yasui.command.reset` | Reset Yasui's counters and statistics. This will not reload the configurations and operation status. |
| `/yasui reload` | `yasui.command.reload` | Reload the plugin and configuration, check and update all the settings/operations/rule definitions as well as reset all counters. |

### Configuration example

`config.yml`

```
language: en_US
enable: true  # global switch
scan_interval_tick: 600
broadcast: CHAT # CHAT | SUBTITLE | ACTIONBAR | ADMIN_CHAT | NONE
top_listing: 10
modules: # Comment out any of the below will disable all its operations.
- entity_ai_suppressor
- entity_culler
- redstone_suppressor
- random_tick_speed
- command_executor
```

Operation files are placed under `operations/` directory, with operation name as the file name, and module name as root variable name in the file, along with its parameters.

Operation names use hyphens, while feature module names use underscores.

* Operation: `suppress-entity-ai` - `operations/suppress-entity-ai.yml`

```
# Suppress entity AI on engage, or restore them on release.
entity_ai_suppressor:
  method: NO_TARGETING # NO_TARGETING | NO_AI | NERFING
  exclude: # entities won't be suppressed, typically used with mob farms that take adv of entity anger
    type:
    - PIG_ZOMBIE
    - ENDERMAN
    tagged: false  # has custom name or tag
    tamed: false  # has owner
```

* Operation: `cull-entity` - `operations/cull-entity.yml`

```
# Cull mobs and disable new mob spawns on engage, enable new mob spawns on release.
entity_culler:
  excluded:
    type:
    - DOLPHIN
    - SNOWMAN
    tagged: true
    tamed: true
  per_chunk_limit: 12
  per_region_limit: 30
```

* Operation: `suppress-redstone` - `operations/suppress-redstone.yml`

```
# Suppress redstone currents on engage, lift cancellation on release.
# Note: Yasui should always set NewCurrent = OldCurrent to keep consistency of redstone mechanics.
redstone_suppressor:
  event_thresholds:
    count_per_chunk: 12000 # 12000 events in 'scan_interval_tick'
    count_piston_per_chunk: 120 #  120 piston events in 'scan_interval_tick'
  supress_chunk_region: 1 # redstone in nearby 3x3 chunks will be supressed
```

* Operation: `adjust-random-tick-speed` - `operations/adjust-random-tick-speed.yml`

```
# Decrease random tick speed by 1 on engage, increase by 1 on release.
random_tick_speed:
  min: 1
  max: 3
```

* Operation: `custom-command` - `operations/custom-command.yml`

```
# Execute command on engage or release.
command_executor:
  engage: 'essentials:killall entities all'
  release: '' # empty string will not do anything
```

Rule files are placed under `rules/` directory.

* `rules/suppress-ai.yml` - Example rule to suppress AI on high mob load. 

```
enabled: true
operations: 
- 'suppress-entity-ai'
worlds:
- world
- world_nether
- world_the_end
engage:
  condition: tps_1m < 18.0 && world_living_entities > 2000
  message: '&b[YASUI] &c[ENGAGED] &6Entity AI Suppressed'
release:
  condition: tps_1m > 19.5
  message: '&b[YASUI] &a[RELEASED] &6Entity AI Recovered'
```

* `rules/adjust-random-tick.yml` - Example rule to auto adjust random tick speed according to server load.

```
enabled: true
operations: 
- 'adjust-random-tick-speed'
worlds:
- world
- world_nether
- world_the_end
engage:
  condition: tps_5m < 17.0
  message: '&b[YASUI] &c[ENGAGED] &6Random Tick Speed: &d{world_random_tick_speed}'
release:
  condition: tps_5m > 19.0
  message: '&b[YASUI] &c[RELEASED] &6Random Tick Speed: &d{world_random_tick_speed}'
```

* `rules/suppress-redstone.yml`

```
enabled: true
operations: 
- 'suppress-redstone'
worlds:
- world
- world_nether
- world_the_end
engage:
  condition: tps_5m < 15.0
  message: '&b[YASUI] &c[ENGAGED] &6Redstone Suppressed'
release:
  condition: tps_5m > 19.0
  message: '&b[YASUI] &c[RELEASED] &6Redstone Recovered'
```

* `rules/cull-entity.yml`

```
enabled: true
operations: 
- 'cull-entity'
worlds:
- world
- world_nether
- world_the_end
engage:
  condition: tps_5m < 17.0 && world_entity > 2000
  message: '&b[YASUI] &c[ENGAGED] &6EntityLimit Engaged'
release:
  condition: tps_5m > 19.0
  message: '&b[YASUI] &c[RELEASED] &6EntityLimit Released'
```

**Comment by phoenixlzx** [comment]
问题：

- [ ] rules 不断被重复触发、重复发广播
- [ ] 手动 engage/release operation 需要命令反馈

**Comment by phoenixlzx** [comment]
新需求： region

`region/region-name.yml`

```
region:
  maxX: 100
  maxY: 255
  maxZ: 100
  minX: -500
  minY: 0
  minZ: -300
bypass:
  - cull-entity  # rule names
  - suppress-redstone
```

**Comment by phoenixlzx** [comment]
* New module `untrack-entity`

Force untrack entity on chunk unload event, and set track on player nearby.

`operations/untrack-entity.yml`

```
untrack_entity:
  # when nearby player is within this range, force set entity to be tracked
  hard-minimum-range: 32
```

`rules/untrack-entity.yml`

```
enabled: true
operations: 
- 'untrack-entity'
worlds:
- world
- world_nether
- world_the_end
engage:
  condition: ''
  message: ''
release:
  condition: ''
  message: ''
```

**Comment by phoenixlzx** [comment]
Global mobcap implementation (paper)

* Remove entity limit implementation from `operations/cull-entity`
* Implement `operations/mobcap` using Paper API and Spigot API (fallback)

API reference:

* https://papermc.io/javadocs/paper/1.14/com/destroystokyo/paper/event/entity/PreCreatureSpawnEvent.html
* https://papermc.io/javadocs/paper/1.14/com/destroystokyo/paper/event/entity/PlayerNaturallySpawnCreaturesEvent.html
* https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.html (as fallback)

Module `mobcap`

Operation `operations/mobcap.yml`

If engaged, new mob will not naturally spawn when total mob count is higher than hard limit, till the amount is below soft limit.

```
mobcap:
  soft: 1200
  hard: 1500
```

Rule `rule/mobcap.yml`

```
enabled: false
operations: 
- 'mobcap'
worlds:
- world
- world_nether
- world_the_end
engage:
  condition: tps_5m < 17.0 && world_living_entities > 1500
  message: '&b[YASUI] &c[ENGAGED] &6Mob spawn reduced: &d{world_mobcap_percent}'
release:
  condition: tps_5m > 19.5
  message: '&b[YASUI] &c[RELEASED] &6Mob spawn lifted: &d{world_mobcap_percent}'
```

Dynamic View Distance (Paper)

* Reduce player VD on engage
* Recover player VD on release

API reference

* https://papermc.io/javadocs/paper/1.14/org/bukkit/entity/Player.html#setViewDistance-int-

Module `adjust-view-distance`

Operation `operation/adjust-view-distance.yml`

Reduce player view distance by 1 on engage, and increase by 1 on release, to the minimum or maximum value.

```
adjust-view-distance:
  min: 6
  max: 10
```

Rule `rule/adjust-view-distance.yml`

```
enabled: false
operations: 
- 'adjust-view-distance'
worlds:
- world
- world_nether
- world_the_end
engage:
  condition: tps_5m < 16.0 && world_chunks > 5000
  message: '&b[YASUI] &c[ENGAGED] &6View Distance &d{world_mobcap_percent}'
release:
  condition: tps_5m > 19.0
  message: '&b[YASUI] &c[RELEASED] &6View Distance &d{world_mobcap_percent}'
```
